services:
  - type: web
    name: tokyo-girls-jh-map
    env: node
    buildCommand: "cd frontend && npm install && npm run build && cd ../backend && npm install"
    startCommand: "cd backend && npm start"
    envVars:
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
